language: php

git:
    depth: 1

matrix:
    fast_finish: true
    include:
        - php: 5.5
          sudo: required
        - php: 5.6
          sudo: required
        - php: 7.0
          dist: trusty
          group: edge
        - php: 7.1
          dist: trusty
          group: edge
    allow_failures:
        - php: 7.0
        - php: 7.1

before_install:
  - sudo add-apt-repository -y ppa:gearman-developers/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgearman-dev gearman-job-server
  - pecl install gearman

before_script:
  - sudo /usr/sbin/gearmand --listen=127.0.0.1 --port=123 -d
  - sudo /usr/sbin/gearmand --listen=127.0.0.1 --port=4730 -d
  - composer install --no-interaction

script:
  - phpunit --verbose
