language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm-3.9
          dist: trusty
    allow_failures:
      - php: nightly

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --verbose